"""Emu full-length 16S abundance route."""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .commands import run_command
from .config import load_config
from .validators import resolve_tool

EMU_EXPECTED_OUTPUTS = ["rel-abundance.tsv", "species-taxonomy.tsv"]


def build_emu_command(
    input_fastq: str,
    database_dir: str,
    output_dir: str,
    threads: int,
    emu_path: str = "emu",
    min_abundance: float | None = None,
    keep_intermediate: bool = False,
) -> list[str]:
    """Build the assumed Emu abundance command.

    The command syntax is isolated here because Emu versions can differ. The
    documented assumption is: `emu abundance --db DB --output-dir OUT --threads N INPUT`.
    """
    cmd = [
        emu_path,
        "abundance",
        "--db",
        database_dir,
        "--output-dir",
        output_dir,
        "--threads",
        str(threads),
    ]
    if min_abundance is not None:
        cmd.extend(["--min-abundance", str(min_abundance)])
    if keep_intermediate:
        cmd.append("--keep-files")
    cmd.append(input_fastq)
    return cmd


def validate_emu_config(config: dict[str, Any]) -> dict[str, Any]:
    emu = config.get("emu_abundance")
    if not isinstance(emu, dict):
        raise ValueError("Missing required emu_abundance configuration section")

    required = ["input_fastq", "database_dir", "output_dir"]
    missing = [key for key in required if not emu.get(key)]
    if missing:
        raise ValueError(f"Missing required Emu config field(s): {', '.join(missing)}")

    threads = int(emu.get("threads", 1))
    if threads < 1:
        raise ValueError("emu_abundance.threads must be >= 1")

    min_abundance = float(emu.get("min_abundance", 0.0001))
    if min_abundance < 0:
        raise ValueError("emu_abundance.min_abundance must be >= 0")

    input_assumption = str(emu.get("input_assumption", "")).strip()
    if emu.get("require_16s_only_input", True) and input_assumption != "full_length_16s":
        raise ValueError(
            "Emu route requires full_length_16s input when require_16s_only_input is true"
        )

    return {
        "enabled": bool(emu.get("enabled", False)),
        "emu_path": str(emu.get("emu_path", "emu")),
        "output_dir": str(emu["output_dir"]),
        "input_fastq": str(emu["input_fastq"]),
        "database_dir": str(emu["database_dir"]),
        "threads": threads,
        "input_assumption": input_assumption,
        "require_16s_only_input": bool(emu.get("require_16s_only_input", True)),
        "min_abundance": min_abundance,
        "keep_intermediate": bool(emu.get("keep_intermediate", False)),
    }


def write_emu_manifest(settings: dict[str, Any], command: list[str]) -> Path:
    output_dir = Path(settings["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "runner": "emu_abundance",
        "created_at_utc": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "input_fastq": settings["input_fastq"],
        "database_dir": settings["database_dir"],
        "input_assumption": settings["input_assumption"],
        "command": command,
        "expected_outputs": [str(output_dir / name) for name in EMU_EXPECTED_OUTPUTS],
        "notes": (
            "Emu estimates relative abundance for full-length 16S-compatible reads; "
            "no biological interpretation is generated by this harness."
        ),
    }
    manifest_path = output_dir / "emu_run_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest_path


def run_emu_from_config(config: dict[str, Any]) -> dict[str, Any]:
    settings = validate_emu_config(config)
    Path(settings["output_dir"]).mkdir(parents=True, exist_ok=True)
    emu_executable = resolve_tool("emu", settings["emu_path"])
    command = build_emu_command(
        settings["input_fastq"],
        settings["database_dir"],
        settings["output_dir"],
        settings["threads"],
        emu_path=emu_executable,
        min_abundance=settings["min_abundance"],
        keep_intermediate=settings["keep_intermediate"],
    )
    run_command(command, "Emu full-length 16S abundance estimation")
    manifest_path = write_emu_manifest(settings, command)
    return {
        "mode": "emu_abundance",
        "command": command,
        "manifest": str(manifest_path),
        "expected_outputs": [
            str(Path(settings["output_dir"]) / name) for name in EMU_EXPECTED_OUTPUTS
        ],
    }


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser("Run Emu abundance mode from YAML config")
    parser.add_argument("--config", required=True, help="Project YAML config.")
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()
    try:
        config = load_config(args.config)
        run_emu_from_config(config)
    except Exception as exc:
        logging.error("Emu route failed: %s", exc)
        sys.exit(1)
